Basic Python
1. Split this string


In [2]:

r = "Hi there Sam!"
r = "Hi there Sam!"
print(r.split())
['Hi', 'there', 'Sam!']


['Hi', 'there', 'Sam!']


['Hi', 'there', 'Sam!']

2. Use .format() to print the following string.
Output should be: The diameter of Earth is 12742 kilometers.

In [1]:
plan1 = "Earth"
diam1 = 12742
plan1 = "Earth"
diam1 = 12742
print( 'The diameter of {} is {} kilometers.' .format(plan1,diam1));

The diameter of Earth is 12742 kilometers.


3. In this nest dictionary grab the word "hello"

In [3]:
c = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


4.Numpy

import numpy as np

4.1 Create an array of 10 zeros?

4.2 Create an array of 10 fives?

In [5]:
import numpy as np
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
arra=np.ones(10)*5
print(arra)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
arr1=np.arange(20,35,2)
print(arr1)

[20 22 24 26 28 30 32 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
mat =  np.arange(0, 9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatinate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
import numpy as np
  
s= np.array([1, 2, 3])
t = np.array([4, 5, 6])
  
result = np.concatenate((s, t), axis = 0)
  
print (result)

[1 2 3 4 5 6]


Pandas
8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [11]:
import pandas as pd
stud = [['Delhi', 'India'],
            ['Tokyo', 'Japan'],
            ['New York', 'US']]
  
# Create a DataFrame object
df = pd.DataFrame(stud,
                  columns=['City', 'Country'],
                  index=['1', '2', '3'])

  
# Displaying the Data frame
df

City Country
1     Delhi   India
2     Tokyo   Japan
3  New York      US

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023


In [12]:
import pandas as pd
  
date = pd.date_range(start ='1-1-2023', 
         end ='02-10-2023')
  
for result in date:
    print(result)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


10. Create 2D list to DataFrame

list = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
list1 = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [13]:
import pandas as pd  
list1 = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(list1, columns =['0', '1','2']) 
print(df )

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
